### ISSUE TITLE
Special characters not allowed in headers

### ISSUE THREAD

**Issue by peterjaap** [kiwicommerce/magento2-enhanced-smtp#12]
When sending an email to a client with a special charcter in their name, we got this error;

```
==> var/log/enhanced_smtp.log <==
[2020-09-10 12:47:46] enhancedSmtpLogHandler.CRITICAL: Invalid header value detected [] []
```

When we added the offending header to the log, we got;

```
==> var/log/enhanced_smtp.log <==
[2020-09-10 12:47:46] enhancedSmtpLogHandler.CRITICAL: Invalid header value detected; Véronique Xxxxxx <veroniquexxxxxxx@gmail.com> [] []
```

It seems this is a fairly common issue with Magento 2 and the underlying Zend Mail package, here's a solution; https://github.com/magepal/magento2-gmail-smtp-app/issues/152#issuecomment-640897253

**Comment by peterjaap** [comment]
Your "competitor" fixed it like this; https://github.com/magepal/magento2-gmail-smtp-app/commit/6d7593092a3139ddfa055e91b6c7c9fdad957c9c

**Comment by peterjaap** [comment]
Here you go https://github.com/kiwicommerce/magento2-enhanced-smtp/pull/13

**Comment by kiwi-commerce** [comment]
Hello @peterjaap ,
Thanks for the PR. I have merged it and changes will be released on the next upcoming version.

Thank you.

**Comment by peterjaap** [comment]
@kiwi-commerce there'll be a new PR incoming, this breaks the checkout when one of the three headers (to, from ,reply-to) aren't set. Which is pretty much always :(

**Comment by peterjaap** [comment]
@kiwi-commerce new PR: https://github.com/kiwicommerce/magento2-enhanced-smtp/pull/14
